package eyobkt.restapichangemonitor;

import java.sql.SQLIntegrityConstraintViolationException;

public class PrimaryKeyConstraintViolationException extends SQLIntegrityConstraintViolationException {}